In [1]:
#dependencies (matrix math) 
import numpy as np

In [11]:
#input data
input_data = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
output_labels = np.array([[0],
            [1],
            [1],
            [0]])

print(input_data)
print(output_labels)

(array([1, 1, 1]), array([1, 0, 1]), array([0, 1, 1]), array([0, 0, 1]))
[[0]
 [1]
 [1]
 [0]]


In [3]:
# sigmoid function
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
# 2 weight values
synaptic_weight_0 = 2*np.random.random((3,4)) - 1
synaptic_weight_1 = 2*np.random.random((4,1)) - 1

print(synaptic_weight_0)
print(synaptic_weight_1)

[[ 0.52640764  0.72929114 -0.12515548 -0.58697785]
 [-0.26886671  0.2637666  -0.8036319  -0.09933065]
 [-0.66571907  0.92424676 -0.93892574 -0.52242595]]
[[ 0.59788086]
 [ 0.89512392]
 [-0.15970518]
 [-0.3333144 ]]


In [12]:
for j in range(600):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(layer2_error))) )
        
    #Use it to compute the gradient
    layer2_gradient = layer2_error*activate(layer2,deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer0.T.dot(layer1_gradient)


Error:0.00339371059982


In [13]:
#testing
syn0=synaptic_weight_0
layer1 = activate(np.dot(np.array([0, 1, 1]), syn0))
#print(layer1)
syn0=synaptic_weight_1
layer2 = activate(np.dot(layer1, syn0))
print (layer2)

[ 0.99763207]


In [7]:
syn0=synaptic_weight_0
layer1 = activate(np.dot(np.array([1, 1, 1]), syn0))
#print(layer1)
syn0=synaptic_weight_1
layer2 = activate(np.dot(layer1, syn0))
print (layer2)

[ 0.00443729]
